name: flutter_manga_viewer
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  archive: ^3.3.7
  dyno: ^0.0.4
  fast_immutable_collections: ^9.1.5
  file_picker: ^6.1.1
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  path: ^1.8.3
  path_provider: ^2.0.15
  uuid: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  custom_lint: ^0.5.7
  riverpod_lint: ^2.3.7

flutter:
  assets:
    - assets/waiting.png
  uses-material-design: true
